version: '3'
services:
        web:
                image: melody_mates
                build: .
                env_file:
                        - .env # This file is optional; defaults will be used if it does not exist
                ports:
                        - "8404:8404"
                volumes:
                        - ./instance:/instance
                restart: unless-stopped
